mybatis-plus:
  mapper-locations: classpath*:com/mzj/meetingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0 代表主键自增
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: cy19990920
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml
