server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://mzj:mzj123@localhost:8761/eureka/

spring:
  application:
    name: Zuul-Service

zuul:
  prefix: "/meetingfilm/" #\u7EDF\u4E00\u524D\u7F00
  routes:
    meetingfilm-user:
      path: /userapi/**
      serviceId: user-service
      retryable: true   #\u662F\u5426\u5141\u8BB8\u91CD\u8BD5
    meetingfilm-cinema:
      path: /cinemaapi/**
      serviceId: cinema-service
      retryable: true
    meetingfilm-film:
      path: /filmapi/**
      serviceId: film-service
      retryable: true
    meetingfilm-hall:
      path: /hallapi/**
      serviceId: hall-service
      retryable: true
#  routes:  ##\u8DEF\u7531\u89C4\u5219
#    film-service:  ## application.name -> \u670D\u52A1\u540D\u79F0
#     path: /film-api/**  #\u5339\u914D\u89C4\u5219
#    cinema-service:
#      path: /cinema-api/**
#    user-service:
#      path: /user-api/**

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

logging:
  config: classpath:logback.xml